volumes:
  transmission:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.10.0.11,rw,nfsvers=3,nolock
      device: ":/volume/fbc954de-d34f-4385-aa6e-3ddd8e0ccd7e/.srv/.unifi-drive/transmission/.data"
