version: "3.3"

services:
  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    environment:
      - PLEX_CLAIM=$PLEX_CLAIM
      - TZ=$TZ
    volumes:
      - /docker/plex/database:/config
      - /docker/plex/transcode/temp:/transcode
      - plex:/data
    network_mode: host
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
